
// This file has been generated by the GUI designer. Do not modify.
namespace CatEye.UI.Gtk.Widgets
{
	public partial class FrozenPanel
	{
		private global::Gtk.HBox hbox1;
		private global::Gtk.Image image6;
		private global::Gtk.Label label1;
		private global::Gtk.Button unfreeze_button;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget CatEye.UI.Gtk.Widgets.FrozenPanel
			global::Stetic.BinContainer.Attach (this);
			this.Name = "CatEye.UI.Gtk.Widgets.FrozenPanel";
			// Container child CatEye.UI.Gtk.Widgets.FrozenPanel.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 2;
			// Container child hbox1.Gtk.Box+BoxChild
			this.image6 = new global::Gtk.Image ();
			this.image6.Name = "image6";
			this.image6.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("CatEye.UI.Gtk.Widgets.res.snowflake.png");
			this.hbox1.Add (this.image6);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.image6]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			w1.Padding = ((uint)(3));
			// Container child hbox1.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.Xalign = 0F;
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Frozen here</b>");
			this.label1.UseMarkup = true;
			this.hbox1.Add (this.label1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label1]));
			w2.Position = 1;
			// Container child hbox1.Gtk.Box+BoxChild
			this.unfreeze_button = new global::Gtk.Button ();
			this.unfreeze_button.CanFocus = true;
			this.unfreeze_button.Name = "unfreeze_button";
			this.unfreeze_button.UseUnderline = true;
			this.unfreeze_button.Label = global::Mono.Unix.Catalog.GetString ("Unfreeze");
			this.hbox1.Add (this.unfreeze_button);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.unfreeze_button]));
			w3.Position = 2;
			this.Add (this.hbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.unfreeze_button.Clicked += new global::System.EventHandler (this.OnUnfreezeButtonClicked);
		}
	}
}
