
// This file has been generated by the GUI designer. Do not modify.
namespace CatEye.UI.Gtk.Widgets
{
	public partial class PreScaleSelectorWidget
	{
		private global::Gtk.HBox hbox;
		private global::Gtk.Label label1;
		private global::Gtk.HScale preScale_hscale;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget CatEye.UI.Gtk.Widgets.PreScaleSelectorWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "CatEye.UI.Gtk.Widgets.PreScaleSelectorWidget";
			// Container child CatEye.UI.Gtk.Widgets.PreScaleSelectorWidget.Gtk.Container+ContainerChild
			this.hbox = new global::Gtk.HBox ();
			this.hbox.Name = "hbox";
			this.hbox.Spacing = 4;
			// Container child hbox.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Downscale image by:");
			this.hbox.Add (this.label1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox [this.label1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox.Gtk.Box+BoxChild
			this.preScale_hscale = new global::Gtk.HScale (null);
			this.preScale_hscale.CanFocus = true;
			this.preScale_hscale.Name = "preScale_hscale";
			this.preScale_hscale.Adjustment.Lower = 1;
			this.preScale_hscale.Adjustment.Upper = 8;
			this.preScale_hscale.Adjustment.PageIncrement = 1;
			this.preScale_hscale.Adjustment.StepIncrement = 1;
			this.preScale_hscale.Adjustment.Value = 1;
			this.preScale_hscale.DrawValue = true;
			this.preScale_hscale.Digits = 0;
			this.preScale_hscale.ValuePos = ((global::Gtk.PositionType)(1));
			this.hbox.Add (this.preScale_hscale);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox [this.preScale_hscale]));
			w2.PackType = ((global::Gtk.PackType)(1));
			w2.Position = 1;
			this.Add (this.hbox);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Show ();
		}
	}
}
