
// This file has been generated by the GUI designer. Do not modify.
namespace CatEye.UI.Gtk.Widgets
{
	public partial class RawPreviewWidget
	{
		private global::Gtk.VBox vbox2;
		private global::Gtk.Label identification_label;
		private global::Gtk.Image thumb_image;
		private global::Gtk.Label origsize_label;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget CatEye.UI.Gtk.Widgets.RawPreviewWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "CatEye.UI.Gtk.Widgets.RawPreviewWidget";
			// Container child CatEye.UI.Gtk.Widgets.RawPreviewWidget.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.identification_label = new global::Gtk.Label ();
			this.identification_label.Name = "identification_label";
			this.identification_label.Xalign = 0F;
			this.identification_label.LabelProp = global::Mono.Unix.Catalog.GetString ("<i>Select a file...</i>");
			this.identification_label.UseMarkup = true;
			this.vbox2.Add (this.identification_label);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.identification_label]));
			w1.Position = 0;
			// Container child vbox2.Gtk.Box+BoxChild
			this.thumb_image = new global::Gtk.Image ();
			this.thumb_image.WidthRequest = 200;
			this.thumb_image.HeightRequest = 200;
			this.thumb_image.Name = "thumb_image";
			this.vbox2.Add (this.thumb_image);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.thumb_image]));
			w2.Position = 1;
			// Container child vbox2.Gtk.Box+BoxChild
			this.origsize_label = new global::Gtk.Label ();
			this.origsize_label.Name = "origsize_label";
			this.origsize_label.Xalign = 0F;
			this.origsize_label.LabelProp = global::Mono.Unix.Catalog.GetString ("Original size:");
			this.origsize_label.UseMarkup = true;
			this.vbox2.Add (this.origsize_label);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.origsize_label]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
