
// This file has been generated by the GUI designer. Do not modify.
namespace CatEye
{
	public partial class FrozenPanel
	{
		private global::Gtk.HBox hbox1;

		private global::Gtk.ToggleButton view_togglebutton;

		private global::Gtk.Button unfreeze_button;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget CatEye.FrozenPanel
			global::Stetic.BinContainer.Attach (this);
			this.Name = "CatEye.FrozenPanel";
			// Container child CatEye.FrozenPanel.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.view_togglebutton = new global::Gtk.ToggleButton ();
			this.view_togglebutton.CanFocus = true;
			this.view_togglebutton.Name = "view_togglebutton";
			this.view_togglebutton.UseUnderline = true;
			this.view_togglebutton.Active = true;
			this.view_togglebutton.Label = global::Mono.Unix.Catalog.GetString ("View");
			this.hbox1.Add (this.view_togglebutton);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.view_togglebutton]));
			w1.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.unfreeze_button = new global::Gtk.Button ();
			this.unfreeze_button.CanFocus = true;
			this.unfreeze_button.Name = "unfreeze_button";
			this.unfreeze_button.UseUnderline = true;
			this.unfreeze_button.Label = global::Mono.Unix.Catalog.GetString ("Unfreeze");
			this.hbox1.Add (this.unfreeze_button);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.unfreeze_button]));
			w2.Position = 1;
			this.Add (this.hbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.view_togglebutton.Released += new global::System.EventHandler (this.OnViewTogglebuttonReleased);
			this.unfreeze_button.Clicked += new global::System.EventHandler (this.OnUnfreezeButtonClicked);
		}
	}
}
