// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace CatEye {
    
    
    public partial class CompressionStageOperationParametersWidget {
        
        private Gtk.Table table2;
        
        private Gtk.Entry bloha_entry;
        
        private Gtk.Label label3;
        
        private Gtk.Label label6;
        
        private Gtk.Entry power_entry;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget CatEye.CompressionStageOperationParametersWidget
            Stetic.BinContainer.Attach(this);
            this.Name = "CatEye.CompressionStageOperationParametersWidget";
            // Container child CatEye.CompressionStageOperationParametersWidget.Gtk.Container+ContainerChild
            this.table2 = new Gtk.Table(((uint)(2)), ((uint)(2)), true);
            this.table2.Name = "table2";
            this.table2.RowSpacing = ((uint)(6));
            this.table2.ColumnSpacing = ((uint)(6));
            // Container child table2.Gtk.Table+TableChild
            this.bloha_entry = new Gtk.Entry();
            this.bloha_entry.CanFocus = true;
            this.bloha_entry.Name = "bloha_entry";
            this.bloha_entry.Text = Mono.Unix.Catalog.GetString("0.01");
            this.bloha_entry.IsEditable = true;
            this.bloha_entry.WidthChars = 6;
            this.table2.Add(this.bloha_entry);
            Gtk.Table.TableChild w1 = ((Gtk.Table.TableChild)(this.table2[this.bloha_entry]));
            w1.TopAttach = ((uint)(1));
            w1.BottomAttach = ((uint)(2));
            w1.LeftAttach = ((uint)(1));
            w1.RightAttach = ((uint)(2));
            w1.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.label3 = new Gtk.Label();
            this.label3.Name = "label3";
            this.label3.Xalign = 1F;
            this.label3.LabelProp = Mono.Unix.Catalog.GetString("Power:");
            this.table2.Add(this.label3);
            Gtk.Table.TableChild w2 = ((Gtk.Table.TableChild)(this.table2[this.label3]));
            w2.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.label6 = new Gtk.Label();
            this.label6.Name = "label6";
            this.label6.Xalign = 1F;
            this.label6.LabelProp = Mono.Unix.Catalog.GetString("Bloha:");
            this.table2.Add(this.label6);
            Gtk.Table.TableChild w3 = ((Gtk.Table.TableChild)(this.table2[this.label6]));
            w3.TopAttach = ((uint)(1));
            w3.BottomAttach = ((uint)(2));
            w3.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.power_entry = new Gtk.Entry();
            this.power_entry.CanFocus = true;
            this.power_entry.Name = "power_entry";
            this.power_entry.Text = Mono.Unix.Catalog.GetString("0.7");
            this.power_entry.IsEditable = true;
            this.power_entry.WidthChars = 6;
            this.table2.Add(this.power_entry);
            Gtk.Table.TableChild w4 = ((Gtk.Table.TableChild)(this.table2[this.power_entry]));
            w4.LeftAttach = ((uint)(1));
            w4.RightAttach = ((uint)(2));
            w4.YOptions = ((Gtk.AttachOptions)(4));
            this.Add(this.table2);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Hide();
            this.power_entry.Changed += new System.EventHandler(this.OnPowerEntryChanged);
            this.bloha_entry.Changed += new System.EventHandler(this.OnBlohaEntryChanged);
        }
    }
}
