
// This file has been generated by the GUI designer. Do not modify.
namespace CatEye
{
	public partial class RotateStageOperationParametersWidget
	{
		private global::Gtk.Table table1;
		private global::Gtk.SpinButton angle_spinbutton;
		private global::Gtk.Label label7;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget CatEye.RotateStageOperationParametersWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "CatEye.RotateStageOperationParametersWidget";
			// Container child CatEye.RotateStageOperationParametersWidget.Gtk.Container+ContainerChild
			this.table1 = new global::Gtk.Table (((uint)(1)), ((uint)(2)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			this.table1.BorderWidth = ((uint)(2));
			// Container child table1.Gtk.Table+TableChild
			this.angle_spinbutton = new global::Gtk.SpinButton (-180, 180, 1);
			this.angle_spinbutton.CanFocus = true;
			this.angle_spinbutton.Name = "angle_spinbutton";
			this.angle_spinbutton.Adjustment.PageIncrement = 1;
			this.angle_spinbutton.ClimbRate = 0.1;
			this.angle_spinbutton.Digits = ((uint)(1));
			this.angle_spinbutton.Numeric = true;
			this.angle_spinbutton.Value = 45;
			this.table1.Add (this.angle_spinbutton);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table1 [this.angle_spinbutton]));
			w1.LeftAttach = ((uint)(1));
			w1.RightAttach = ((uint)(2));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.Xalign = 1F;
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Angle:");
			this.table1.Add (this.label7);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1 [this.label7]));
			w2.XPadding = ((uint)(2));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			this.Add (this.table1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.angle_spinbutton.ValueChanged += new global::System.EventHandler (this.OnAngleSpinbuttonValueChanged);
		}
	}
}
