
// This file has been generated by the GUI designer. Do not modify.
namespace CatEye
{
	public partial class CompressionStageOperationParametersWidget
	{
		private global::Gtk.Table table1;

		private global::Gtk.HScale dark_preserving_hscale;

		private global::Gtk.SpinButton dark_preserving_spinbutton;

		private global::Gtk.Label label12;

		private global::Gtk.Label label7;

		private global::Gtk.HScale power_hscale;

		private global::Gtk.SpinButton power_spinbutton;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget CatEye.CompressionStageOperationParametersWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "CatEye.CompressionStageOperationParametersWidget";
			// Container child CatEye.CompressionStageOperationParametersWidget.Gtk.Container+ContainerChild
			this.table1 = new global::Gtk.Table (((uint)(2)), ((uint)(3)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			this.table1.BorderWidth = ((uint)(4));
			// Container child table1.Gtk.Table+TableChild
			this.dark_preserving_hscale = new global::Gtk.HScale (null);
			this.dark_preserving_hscale.CanFocus = true;
			this.dark_preserving_hscale.Name = "dark_preserving_hscale";
			this.dark_preserving_hscale.Adjustment.Upper = 1;
			this.dark_preserving_hscale.Adjustment.PageIncrement = 0.01;
			this.dark_preserving_hscale.Adjustment.StepIncrement = 0.001;
			this.dark_preserving_hscale.Adjustment.Value = 0.001;
			this.dark_preserving_hscale.DrawValue = false;
			this.dark_preserving_hscale.Digits = 3;
			this.dark_preserving_hscale.ValuePos = ((global::Gtk.PositionType)(1));
			this.table1.Add (this.dark_preserving_hscale);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table1[this.dark_preserving_hscale]));
			w1.TopAttach = ((uint)(1));
			w1.BottomAttach = ((uint)(2));
			w1.LeftAttach = ((uint)(1));
			w1.RightAttach = ((uint)(2));
			w1.XOptions = ((global::Gtk.AttachOptions)(4));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.dark_preserving_spinbutton = new global::Gtk.SpinButton (0, 1, 0.01);
			this.dark_preserving_spinbutton.CanFocus = true;
			this.dark_preserving_spinbutton.Name = "dark_preserving_spinbutton";
			this.dark_preserving_spinbutton.Adjustment.PageIncrement = 0.005;
			this.dark_preserving_spinbutton.ClimbRate = 0.01;
			this.dark_preserving_spinbutton.Digits = ((uint)(2));
			this.dark_preserving_spinbutton.Numeric = true;
			this.table1.Add (this.dark_preserving_spinbutton);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1[this.dark_preserving_spinbutton]));
			w2.TopAttach = ((uint)(1));
			w2.BottomAttach = ((uint)(2));
			w2.LeftAttach = ((uint)(2));
			w2.RightAttach = ((uint)(3));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label12 = new global::Gtk.Label ();
			this.label12.Name = "label12";
			this.label12.Xalign = 1f;
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString ("Dark preserving:");
			this.table1.Add (this.label12);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1[this.label12]));
			w3.TopAttach = ((uint)(1));
			w3.BottomAttach = ((uint)(2));
			w3.XPadding = ((uint)(2));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.Xalign = 1f;
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Power:");
			this.table1.Add (this.label7);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1[this.label7]));
			w4.XPadding = ((uint)(2));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.power_hscale = new global::Gtk.HScale (null);
			this.power_hscale.CanFocus = true;
			this.power_hscale.Name = "power_hscale";
			this.power_hscale.Adjustment.Upper = 1;
			this.power_hscale.Adjustment.PageIncrement = 0.05;
			this.power_hscale.Adjustment.StepIncrement = 0.01;
			this.power_hscale.Adjustment.Value = 0.001;
			this.power_hscale.DrawValue = false;
			this.power_hscale.Digits = 3;
			this.power_hscale.ValuePos = ((global::Gtk.PositionType)(1));
			this.table1.Add (this.power_hscale);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1[this.power_hscale]));
			w5.LeftAttach = ((uint)(1));
			w5.RightAttach = ((uint)(2));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.power_spinbutton = new global::Gtk.SpinButton (0, 1, 0.1);
			this.power_spinbutton.CanFocus = true;
			this.power_spinbutton.Name = "power_spinbutton";
			this.power_spinbutton.Adjustment.PageIncrement = 0.05;
			this.power_spinbutton.ClimbRate = 0.01;
			this.power_spinbutton.Digits = ((uint)(2));
			this.power_spinbutton.Numeric = true;
			this.table1.Add (this.power_spinbutton);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1[this.power_spinbutton]));
			w6.LeftAttach = ((uint)(2));
			w6.RightAttach = ((uint)(3));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			this.Add (this.table1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.power_spinbutton.ValueChanged += new global::System.EventHandler (this.OnPowerSpinbuttonValueChanged);
			this.power_hscale.ChangeValue += new global::Gtk.ChangeValueHandler (this.OnPowerHscaleChangeValue);
			this.dark_preserving_spinbutton.ValueChanged += new global::System.EventHandler (this.OnDarkPreservingSpinbuttonValueChanged);
			this.dark_preserving_hscale.ChangeValue += new global::Gtk.ChangeValueHandler (this.OnDarkPreservingHscaleChangeValue);
		}
	}
}
