
// This file has been generated by the GUI designer. Do not modify.
namespace CatEye
{
	public partial class UltraSharpStageOperationParametersWidget
	{
		private global::Gtk.Table table1;

		private global::Gtk.Label label12;

		private global::Gtk.Label label13;

		private global::Gtk.Label label14;

		private global::Gtk.Label label15;

		private global::Gtk.Label label7;

		private global::Gtk.Entry limit_entry;

		private global::Gtk.Entry points_entry;

		private global::Gtk.Entry power_entry;

		private global::Gtk.Entry radius_entry;

		private global::Gtk.Entry weight_entry;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget CatEye.UltraSharpStageOperationParametersWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "CatEye.UltraSharpStageOperationParametersWidget";
			// Container child CatEye.UltraSharpStageOperationParametersWidget.Gtk.Container+ContainerChild
			this.table1 = new global::Gtk.Table (((uint)(5)), ((uint)(2)), true);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.label12 = new global::Gtk.Label ();
			this.label12.Name = "label12";
			this.label12.Xalign = 1f;
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString ("Radius (part):");
			this.table1.Add (this.label12);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table1[this.label12]));
			w1.TopAttach = ((uint)(1));
			w1.BottomAttach = ((uint)(2));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label13 = new global::Gtk.Label ();
			this.label13.Name = "label13";
			this.label13.Xalign = 1f;
			this.label13.LabelProp = global::Mono.Unix.Catalog.GetString ("Weight:");
			this.table1.Add (this.label13);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1[this.label13]));
			w2.TopAttach = ((uint)(2));
			w2.BottomAttach = ((uint)(3));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label14 = new global::Gtk.Label ();
			this.label14.Name = "label14";
			this.label14.Xalign = 1f;
			this.label14.LabelProp = global::Mono.Unix.Catalog.GetString ("Limit:");
			this.table1.Add (this.label14);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1[this.label14]));
			w3.TopAttach = ((uint)(3));
			w3.BottomAttach = ((uint)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label15 = new global::Gtk.Label ();
			this.label15.Name = "label15";
			this.label15.Xalign = 1f;
			this.label15.LabelProp = global::Mono.Unix.Catalog.GetString ("Points:");
			this.table1.Add (this.label15);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1[this.label15]));
			w4.TopAttach = ((uint)(4));
			w4.BottomAttach = ((uint)(5));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.Xalign = 1f;
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Power:");
			this.table1.Add (this.label7);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1[this.label7]));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.limit_entry = new global::Gtk.Entry ();
			this.limit_entry.CanFocus = true;
			this.limit_entry.Name = "limit_entry";
			this.limit_entry.Text = global::Mono.Unix.Catalog.GetString ("0.3");
			this.limit_entry.IsEditable = true;
			this.limit_entry.WidthChars = 6;
			this.limit_entry.InvisibleChar = '●';
			this.table1.Add (this.limit_entry);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1[this.limit_entry]));
			w6.TopAttach = ((uint)(3));
			w6.BottomAttach = ((uint)(4));
			w6.LeftAttach = ((uint)(1));
			w6.RightAttach = ((uint)(2));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.points_entry = new global::Gtk.Entry ();
			this.points_entry.CanFocus = true;
			this.points_entry.Name = "points_entry";
			this.points_entry.Text = global::Mono.Unix.Catalog.GetString ("200");
			this.points_entry.IsEditable = true;
			this.points_entry.WidthChars = 6;
			this.points_entry.InvisibleChar = '●';
			this.table1.Add (this.points_entry);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1[this.points_entry]));
			w7.TopAttach = ((uint)(4));
			w7.BottomAttach = ((uint)(5));
			w7.LeftAttach = ((uint)(1));
			w7.RightAttach = ((uint)(2));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.power_entry = new global::Gtk.Entry ();
			this.power_entry.CanFocus = true;
			this.power_entry.Name = "power_entry";
			this.power_entry.Text = global::Mono.Unix.Catalog.GetString ("0.3");
			this.power_entry.IsEditable = true;
			this.power_entry.WidthChars = 6;
			this.power_entry.InvisibleChar = '●';
			this.table1.Add (this.power_entry);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1[this.power_entry]));
			w8.LeftAttach = ((uint)(1));
			w8.RightAttach = ((uint)(2));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.radius_entry = new global::Gtk.Entry ();
			this.radius_entry.CanFocus = true;
			this.radius_entry.Name = "radius_entry";
			this.radius_entry.Text = global::Mono.Unix.Catalog.GetString ("0.1");
			this.radius_entry.IsEditable = true;
			this.radius_entry.WidthChars = 6;
			this.radius_entry.InvisibleChar = '●';
			this.table1.Add (this.radius_entry);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1[this.radius_entry]));
			w9.TopAttach = ((uint)(1));
			w9.BottomAttach = ((uint)(2));
			w9.LeftAttach = ((uint)(1));
			w9.RightAttach = ((uint)(2));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.weight_entry = new global::Gtk.Entry ();
			this.weight_entry.CanFocus = true;
			this.weight_entry.Name = "weight_entry";
			this.weight_entry.Text = global::Mono.Unix.Catalog.GetString ("80");
			this.weight_entry.IsEditable = true;
			this.weight_entry.WidthChars = 6;
			this.weight_entry.InvisibleChar = '●';
			this.table1.Add (this.weight_entry);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1[this.weight_entry]));
			w10.TopAttach = ((uint)(2));
			w10.BottomAttach = ((uint)(3));
			w10.LeftAttach = ((uint)(1));
			w10.RightAttach = ((uint)(2));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			this.Add (this.table1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.weight_entry.Changed += new global::System.EventHandler (this.OnWeightEntryChanged);
			this.radius_entry.Changed += new global::System.EventHandler (this.OnRadiusEntryChanged);
			this.power_entry.Changed += new global::System.EventHandler (this.OnPowerEntryChanged);
			this.points_entry.Changed += new global::System.EventHandler (this.OnPointsEntryChanged);
			this.limit_entry.Changed += new global::System.EventHandler (this.OnLimitEntryChanged);
		}
	}
}
