
// This file has been generated by the GUI designer. Do not modify.
namespace CatEye
{
	public partial class DownscalingStageOperationParametersWidget
	{
		private global::Gtk.ComboBox scale_combobox;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget CatEye.DownscalingStageOperationParametersWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "CatEye.DownscalingStageOperationParametersWidget";
			// Container child CatEye.DownscalingStageOperationParametersWidget.Gtk.Container+ContainerChild
			this.scale_combobox = global::Gtk.ComboBox.NewText ();
			this.scale_combobox.Name = "scale_combobox";
			this.Add (this.scale_combobox);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.scale_combobox.Changed += new global::System.EventHandler (this.OnScaleComboboxChanged);
		}
	}
}
