
// This file has been generated by the GUI designer. Do not modify.
namespace CatEye
{
	public partial class ToneStageOperationParametersWidget
	{
		private global::Gtk.HBox hbox1;
		private global::CatEye.ToneSelectorWidget toneselectorwidget1;
		private global::Gtk.VBox vbox2;
		private global::Gtk.Label r_label;
		private global::Gtk.Label g_label;
		private global::Gtk.Label b_label;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget CatEye.ToneStageOperationParametersWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "CatEye.ToneStageOperationParametersWidget";
			// Container child CatEye.ToneStageOperationParametersWidget.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.toneselectorwidget1 = new global::CatEye.ToneSelectorWidget ();
			this.toneselectorwidget1.Events = ((global::Gdk.EventMask)(790));
			this.toneselectorwidget1.Name = "toneselectorwidget1";
			this.hbox1.Add (this.toneselectorwidget1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.toneselectorwidget1]));
			w1.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.r_label = new global::Gtk.Label ();
			this.r_label.Name = "r_label";
			this.r_label.LabelProp = global::Mono.Unix.Catalog.GetString ("label1");
			this.vbox2.Add (this.r_label);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.r_label]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.g_label = new global::Gtk.Label ();
			this.g_label.Name = "g_label";
			this.g_label.LabelProp = global::Mono.Unix.Catalog.GetString ("label2");
			this.vbox2.Add (this.g_label);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.g_label]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.b_label = new global::Gtk.Label ();
			this.b_label.Name = "b_label";
			this.b_label.LabelProp = global::Mono.Unix.Catalog.GetString ("label3");
			this.vbox2.Add (this.b_label);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.b_label]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			this.hbox1.Add (this.vbox2);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox2]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			this.Add (this.hbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
