// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace CatEye {
    
    
    public partial class DownscalingStageOperationParametersWidget {
        
        private Gtk.ComboBox scale_combobox;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget CatEye.DownscalingStageOperationParametersWidget
            Stetic.BinContainer.Attach(this);
            this.Name = "CatEye.DownscalingStageOperationParametersWidget";
            // Container child CatEye.DownscalingStageOperationParametersWidget.Gtk.Container+ContainerChild
            this.scale_combobox = Gtk.ComboBox.NewText();
            this.scale_combobox.Name = "scale_combobox";
            this.Add(this.scale_combobox);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Hide();
            this.scale_combobox.Changed += new System.EventHandler(this.OnScaleComboboxChanged);
        }
    }
}
