
// This file has been generated by the GUI designer. Do not modify.
namespace CatEye
{
	public partial class ScaleStageOperationParametersWidget
	{
		private global::Gtk.Table table1;
		private global::Gtk.SpinButton height_spinbutton;
		private global::Gtk.Label label12;
		private global::Gtk.Label label7;
		private global::Gtk.SpinButton width_spinbutton;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget CatEye.ScaleStageOperationParametersWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "CatEye.ScaleStageOperationParametersWidget";
			// Container child CatEye.ScaleStageOperationParametersWidget.Gtk.Container+ContainerChild
			this.table1 = new global::Gtk.Table (((uint)(2)), ((uint)(2)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			this.table1.BorderWidth = ((uint)(2));
			// Container child table1.Gtk.Table+TableChild
			this.height_spinbutton = new global::Gtk.SpinButton (10, 10000, 10);
			this.height_spinbutton.CanFocus = true;
			this.height_spinbutton.Name = "height_spinbutton";
			this.height_spinbutton.Adjustment.PageIncrement = 100;
			this.height_spinbutton.ClimbRate = 1;
			this.height_spinbutton.Numeric = true;
			this.height_spinbutton.Value = 1000;
			this.table1.Add (this.height_spinbutton);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table1 [this.height_spinbutton]));
			w1.TopAttach = ((uint)(1));
			w1.BottomAttach = ((uint)(2));
			w1.LeftAttach = ((uint)(1));
			w1.RightAttach = ((uint)(2));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label12 = new global::Gtk.Label ();
			this.label12.Name = "label12";
			this.label12.Xalign = 1F;
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString ("Height:");
			this.table1.Add (this.label12);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1 [this.label12]));
			w2.TopAttach = ((uint)(1));
			w2.BottomAttach = ((uint)(2));
			w2.XPadding = ((uint)(2));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.Xalign = 1F;
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Width:");
			this.table1.Add (this.label7);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1 [this.label7]));
			w3.XPadding = ((uint)(2));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.width_spinbutton = new global::Gtk.SpinButton (10, 10000, 10);
			this.width_spinbutton.CanFocus = true;
			this.width_spinbutton.Name = "width_spinbutton";
			this.width_spinbutton.Adjustment.PageIncrement = 100;
			this.width_spinbutton.ClimbRate = 1;
			this.width_spinbutton.Numeric = true;
			this.width_spinbutton.Value = 1000;
			this.table1.Add (this.width_spinbutton);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1 [this.width_spinbutton]));
			w4.LeftAttach = ((uint)(1));
			w4.RightAttach = ((uint)(2));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			this.Add (this.table1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.width_spinbutton.ValueChanged += new global::System.EventHandler (this.OnWidthSpinbuttonValueChanged);
			this.height_spinbutton.ValueChanged += new global::System.EventHandler (this.OnHeightSpinbuttonValueChanged);
		}
	}
}
