
// This file has been generated by the GUI designer. Do not modify.
namespace CatEye
{
	public partial class BrightnessStageOperationParametersWidget
	{
		private global::Gtk.Table table1;

		private global::Gtk.Entry brightness_entry;

		private global::Gtk.Label label2;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget CatEye.BrightnessStageOperationParametersWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "CatEye.BrightnessStageOperationParametersWidget";
			// Container child CatEye.BrightnessStageOperationParametersWidget.Gtk.Container+ContainerChild
			this.table1 = new global::Gtk.Table (((uint)(1)), ((uint)(2)), true);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.brightness_entry = new global::Gtk.Entry ();
			this.brightness_entry.CanFocus = true;
			this.brightness_entry.Name = "brightness_entry";
			this.brightness_entry.Text = global::Mono.Unix.Catalog.GetString ("1");
			this.brightness_entry.IsEditable = true;
			this.brightness_entry.WidthChars = 6;
			this.brightness_entry.InvisibleChar = '●';
			this.table1.Add (this.brightness_entry);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table1[this.brightness_entry]));
			w1.LeftAttach = ((uint)(1));
			w1.RightAttach = ((uint)(2));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.Xalign = 1f;
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Brightness:");
			this.table1.Add (this.label2);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1[this.label2]));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			this.Add (this.table1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.brightness_entry.Changed += new global::System.EventHandler (this.OnBrightnessEntryChanged);
		}
	}
}
