
// This file has been generated by the GUI designer. Do not modify.
namespace CatEye
{
	public partial class StageOperationHolderWidget
	{
		private global::Gtk.VBox vbox;

		private global::CatEye.StageOperationTitleWidget _TitleWidget;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget CatEye.StageOperationHolderWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "CatEye.StageOperationHolderWidget";
			// Container child CatEye.StageOperationHolderWidget.Gtk.Container+ContainerChild
			this.vbox = new global::Gtk.VBox ();
			this.vbox.Name = "vbox";
			this.vbox.Spacing = 6;
			// Container child vbox.Gtk.Box+BoxChild
			this._TitleWidget = new global::CatEye.StageOperationTitleWidget ();
			this._TitleWidget.Events = ((global::Gdk.EventMask)(256));
			this._TitleWidget.Name = "_TitleWidget";
			this._TitleWidget.Active = false;
			this.vbox.Add (this._TitleWidget);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox[this._TitleWidget]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			this.Add (this.vbox);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
