// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace CatEye {
    
    
    public partial class BasicOpsStageOperationParametersWidget {
        
        private Gtk.Table table1;
        
        private Gtk.Entry blue_entry;
        
        private Gtk.Entry brightness_entry;
        
        private Gtk.Entry green_entry;
        
        private Gtk.Label label10;
        
        private Gtk.Label label11;
        
        private Gtk.Label label2;
        
        private Gtk.Label label8;
        
        private Gtk.Label label9;
        
        private Gtk.Entry red_entry;
        
        private Gtk.Entry saturation_entry;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget CatEye.BasicOpsStageOperationParametersWidget
            Stetic.BinContainer.Attach(this);
            this.Name = "CatEye.BasicOpsStageOperationParametersWidget";
            // Container child CatEye.BasicOpsStageOperationParametersWidget.Gtk.Container+ContainerChild
            this.table1 = new Gtk.Table(((uint)(5)), ((uint)(2)), true);
            this.table1.Name = "table1";
            this.table1.RowSpacing = ((uint)(6));
            this.table1.ColumnSpacing = ((uint)(6));
            // Container child table1.Gtk.Table+TableChild
            this.blue_entry = new Gtk.Entry();
            this.blue_entry.CanFocus = true;
            this.blue_entry.Name = "blue_entry";
            this.blue_entry.Text = Mono.Unix.Catalog.GetString("0.8");
            this.blue_entry.IsEditable = true;
            this.blue_entry.WidthChars = 6;
            this.table1.Add(this.blue_entry);
            Gtk.Table.TableChild w1 = ((Gtk.Table.TableChild)(this.table1[this.blue_entry]));
            w1.TopAttach = ((uint)(4));
            w1.BottomAttach = ((uint)(5));
            w1.LeftAttach = ((uint)(1));
            w1.RightAttach = ((uint)(2));
            w1.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.brightness_entry = new Gtk.Entry();
            this.brightness_entry.CanFocus = true;
            this.brightness_entry.Name = "brightness_entry";
            this.brightness_entry.Text = Mono.Unix.Catalog.GetString("0.8");
            this.brightness_entry.IsEditable = true;
            this.brightness_entry.WidthChars = 6;
            this.table1.Add(this.brightness_entry);
            Gtk.Table.TableChild w2 = ((Gtk.Table.TableChild)(this.table1[this.brightness_entry]));
            w2.LeftAttach = ((uint)(1));
            w2.RightAttach = ((uint)(2));
            w2.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.green_entry = new Gtk.Entry();
            this.green_entry.CanFocus = true;
            this.green_entry.Name = "green_entry";
            this.green_entry.Text = Mono.Unix.Catalog.GetString("1.05");
            this.green_entry.IsEditable = true;
            this.green_entry.WidthChars = 6;
            this.table1.Add(this.green_entry);
            Gtk.Table.TableChild w3 = ((Gtk.Table.TableChild)(this.table1[this.green_entry]));
            w3.TopAttach = ((uint)(3));
            w3.BottomAttach = ((uint)(4));
            w3.LeftAttach = ((uint)(1));
            w3.RightAttach = ((uint)(2));
            w3.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label10 = new Gtk.Label();
            this.label10.Name = "label10";
            this.label10.Xalign = 1F;
            this.label10.LabelProp = Mono.Unix.Catalog.GetString("Green:");
            this.table1.Add(this.label10);
            Gtk.Table.TableChild w4 = ((Gtk.Table.TableChild)(this.table1[this.label10]));
            w4.TopAttach = ((uint)(3));
            w4.BottomAttach = ((uint)(4));
            w4.XOptions = ((Gtk.AttachOptions)(4));
            w4.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label11 = new Gtk.Label();
            this.label11.Name = "label11";
            this.label11.Xalign = 1F;
            this.label11.LabelProp = Mono.Unix.Catalog.GetString("Blue:");
            this.table1.Add(this.label11);
            Gtk.Table.TableChild w5 = ((Gtk.Table.TableChild)(this.table1[this.label11]));
            w5.TopAttach = ((uint)(4));
            w5.BottomAttach = ((uint)(5));
            w5.XOptions = ((Gtk.AttachOptions)(4));
            w5.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label2 = new Gtk.Label();
            this.label2.Name = "label2";
            this.label2.Xalign = 1F;
            this.label2.LabelProp = Mono.Unix.Catalog.GetString("Brightness:");
            this.table1.Add(this.label2);
            Gtk.Table.TableChild w6 = ((Gtk.Table.TableChild)(this.table1[this.label2]));
            w6.XOptions = ((Gtk.AttachOptions)(4));
            w6.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label8 = new Gtk.Label();
            this.label8.Name = "label8";
            this.label8.Xalign = 1F;
            this.label8.LabelProp = Mono.Unix.Catalog.GetString("Saturation:");
            this.table1.Add(this.label8);
            Gtk.Table.TableChild w7 = ((Gtk.Table.TableChild)(this.table1[this.label8]));
            w7.TopAttach = ((uint)(1));
            w7.BottomAttach = ((uint)(2));
            w7.XOptions = ((Gtk.AttachOptions)(4));
            w7.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label9 = new Gtk.Label();
            this.label9.Name = "label9";
            this.label9.Xalign = 1F;
            this.label9.LabelProp = Mono.Unix.Catalog.GetString("Red:");
            this.table1.Add(this.label9);
            Gtk.Table.TableChild w8 = ((Gtk.Table.TableChild)(this.table1[this.label9]));
            w8.TopAttach = ((uint)(2));
            w8.BottomAttach = ((uint)(3));
            w8.XOptions = ((Gtk.AttachOptions)(4));
            w8.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.red_entry = new Gtk.Entry();
            this.red_entry.CanFocus = true;
            this.red_entry.Name = "red_entry";
            this.red_entry.Text = Mono.Unix.Catalog.GetString("1.3");
            this.red_entry.IsEditable = true;
            this.red_entry.WidthChars = 6;
            this.table1.Add(this.red_entry);
            Gtk.Table.TableChild w9 = ((Gtk.Table.TableChild)(this.table1[this.red_entry]));
            w9.TopAttach = ((uint)(2));
            w9.BottomAttach = ((uint)(3));
            w9.LeftAttach = ((uint)(1));
            w9.RightAttach = ((uint)(2));
            w9.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.saturation_entry = new Gtk.Entry();
            this.saturation_entry.CanFocus = true;
            this.saturation_entry.Name = "saturation_entry";
            this.saturation_entry.Text = Mono.Unix.Catalog.GetString("0.9");
            this.saturation_entry.IsEditable = true;
            this.saturation_entry.WidthChars = 6;
            this.table1.Add(this.saturation_entry);
            Gtk.Table.TableChild w10 = ((Gtk.Table.TableChild)(this.table1[this.saturation_entry]));
            w10.TopAttach = ((uint)(1));
            w10.BottomAttach = ((uint)(2));
            w10.LeftAttach = ((uint)(1));
            w10.RightAttach = ((uint)(2));
            w10.YOptions = ((Gtk.AttachOptions)(4));
            this.Add(this.table1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Hide();
            this.saturation_entry.Changed += new System.EventHandler(this.OnSaturationEntryChanged);
            this.red_entry.Changed += new System.EventHandler(this.OnRedEntryChanged);
            this.green_entry.Changed += new System.EventHandler(this.OnGreenEntryChanged);
            this.brightness_entry.Changed += new System.EventHandler(this.OnBrightnessEntryChanged);
            this.blue_entry.Changed += new System.EventHandler(this.OnBlueEntryChanged);
        }
    }
}
