
// This file has been generated by the GUI designer. Do not modify.
namespace CatEye
{
	public partial class SaturationStageOperationParametersWidget
	{
		private global::Gtk.Table table1;
		private global::Gtk.Label label8;
		private global::Gtk.Entry saturation_entry;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget CatEye.SaturationStageOperationParametersWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "CatEye.SaturationStageOperationParametersWidget";
			// Container child CatEye.SaturationStageOperationParametersWidget.Gtk.Container+ContainerChild
			this.table1 = new global::Gtk.Table (((uint)(1)), ((uint)(2)), true);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.label8 = new global::Gtk.Label ();
			this.label8.Name = "label8";
			this.label8.Xalign = 1F;
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Saturation:");
			this.table1.Add (this.label8);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table1 [this.label8]));
			w1.XOptions = ((global::Gtk.AttachOptions)(4));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.saturation_entry = new global::Gtk.Entry ();
			this.saturation_entry.CanFocus = true;
			this.saturation_entry.Name = "saturation_entry";
			this.saturation_entry.Text = global::Mono.Unix.Catalog.GetString ("1");
			this.saturation_entry.IsEditable = true;
			this.saturation_entry.WidthChars = 6;
			this.saturation_entry.InvisibleChar = '●';
			this.table1.Add (this.saturation_entry);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1 [this.saturation_entry]));
			w2.LeftAttach = ((uint)(1));
			w2.RightAttach = ((uint)(2));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			this.Add (this.table1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.saturation_entry.Changed += new global::System.EventHandler (this.OnSaturationEntryChanged);
		}
	}
}
