// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace CatEye {
    
    
    public partial class StageOperationHolderWidget {
        
        private Gtk.VBox vbox;
        
        private CatEye.StageOperationTitleWidget _TitleWidget;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget CatEye.StageOperationHolderWidget
            Stetic.BinContainer.Attach(this);
            this.Name = "CatEye.StageOperationHolderWidget";
            // Container child CatEye.StageOperationHolderWidget.Gtk.Container+ContainerChild
            this.vbox = new Gtk.VBox();
            this.vbox.Name = "vbox";
            this.vbox.Spacing = 6;
            // Container child vbox.Gtk.Box+BoxChild
            this._TitleWidget = new CatEye.StageOperationTitleWidget();
            this._TitleWidget.Events = ((Gdk.EventMask)(256));
            this._TitleWidget.Name = "_TitleWidget";
            this._TitleWidget.Active = false;
            this.vbox.Add(this._TitleWidget);
            Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.vbox[this._TitleWidget]));
            w1.Position = 0;
            w1.Expand = false;
            w1.Fill = false;
            this.Add(this.vbox);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Hide();
        }
    }
}
