
// This file has been generated by the GUI designer. Do not modify.
namespace CatEye
{
	public partial class StageOperationTitleWidget
	{
		private global::Gtk.HBox hbox;
		private global::Gtk.CheckButton title_checkbutton;
		private global::Gtk.Label title_label;
		private global::Gtk.ToggleButton view_togglebutton;
		private global::Gtk.ToggleButton freeze_togglebutton;
		private global::Gtk.Button up_button;
		private global::Gtk.Arrow arrow5;
		private global::Gtk.Button down_button;
		private global::Gtk.Arrow arrow6;
		private global::Gtk.Button remove_button;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget CatEye.StageOperationTitleWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "CatEye.StageOperationTitleWidget";
			// Container child CatEye.StageOperationTitleWidget.Gtk.Container+ContainerChild
			this.hbox = new global::Gtk.HBox ();
			this.hbox.Name = "hbox";
			// Container child hbox.Gtk.Box+BoxChild
			this.title_checkbutton = new global::Gtk.CheckButton ();
			this.title_checkbutton.CanFocus = true;
			this.title_checkbutton.Name = "title_checkbutton";
			this.title_checkbutton.Label = global::Mono.Unix.Catalog.GetString ("checkbutton2");
			this.title_checkbutton.DrawIndicator = true;
			this.title_checkbutton.UseUnderline = true;
			this.title_checkbutton.Remove (this.title_checkbutton.Child);
			// Container child title_checkbutton.Gtk.Container+ContainerChild
			this.title_label = new global::Gtk.Label ();
			this.title_label.Name = "title_label";
			this.title_label.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Title</b>");
			this.title_label.UseMarkup = true;
			this.title_label.SingleLineMode = true;
			this.title_checkbutton.Add (this.title_label);
			this.hbox.Add (this.title_checkbutton);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox [this.title_checkbutton]));
			w2.Position = 0;
			w2.Padding = ((uint)(2));
			// Container child hbox.Gtk.Box+BoxChild
			this.view_togglebutton = new global::Gtk.ToggleButton ();
			this.view_togglebutton.CanFocus = true;
			this.view_togglebutton.Name = "view_togglebutton";
			this.view_togglebutton.UseUnderline = true;
			this.view_togglebutton.Relief = ((global::Gtk.ReliefStyle)(2));
			this.view_togglebutton.Label = global::Mono.Unix.Catalog.GetString ("View");
			this.hbox.Add (this.view_togglebutton);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox [this.view_togglebutton]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox.Gtk.Box+BoxChild
			this.freeze_togglebutton = new global::Gtk.ToggleButton ();
			this.freeze_togglebutton.CanFocus = true;
			this.freeze_togglebutton.Name = "freeze_togglebutton";
			this.freeze_togglebutton.UseUnderline = true;
			this.freeze_togglebutton.Relief = ((global::Gtk.ReliefStyle)(2));
			this.freeze_togglebutton.Label = global::Mono.Unix.Catalog.GetString ("Freeze");
			this.hbox.Add (this.freeze_togglebutton);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox [this.freeze_togglebutton]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox.Gtk.Box+BoxChild
			this.up_button = new global::Gtk.Button ();
			this.up_button.WidthRequest = 23;
			this.up_button.CanFocus = true;
			this.up_button.Name = "up_button";
			this.up_button.Relief = ((global::Gtk.ReliefStyle)(2));
			// Container child up_button.Gtk.Container+ContainerChild
			this.arrow5 = new global::Gtk.Arrow (((global::Gtk.ArrowType)(0)), ((global::Gtk.ShadowType)(0)));
			this.arrow5.Name = "arrow5";
			this.up_button.Add (this.arrow5);
			this.up_button.Label = null;
			this.hbox.Add (this.up_button);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox [this.up_button]));
			w6.Position = 3;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox.Gtk.Box+BoxChild
			this.down_button = new global::Gtk.Button ();
			this.down_button.WidthRequest = 23;
			this.down_button.CanFocus = true;
			this.down_button.Name = "down_button";
			this.down_button.Relief = ((global::Gtk.ReliefStyle)(2));
			// Container child down_button.Gtk.Container+ContainerChild
			this.arrow6 = new global::Gtk.Arrow (((global::Gtk.ArrowType)(1)), ((global::Gtk.ShadowType)(0)));
			this.arrow6.Name = "arrow6";
			this.down_button.Add (this.arrow6);
			this.down_button.Label = null;
			this.hbox.Add (this.down_button);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox [this.down_button]));
			w8.Position = 4;
			w8.Expand = false;
			w8.Fill = false;
			// Container child hbox.Gtk.Box+BoxChild
			this.remove_button = new global::Gtk.Button ();
			this.remove_button.CanFocus = true;
			this.remove_button.Name = "remove_button";
			this.remove_button.UseUnderline = true;
			this.remove_button.Relief = ((global::Gtk.ReliefStyle)(2));
			// Container child remove_button.Gtk.Container+ContainerChild
			global::Gtk.Alignment w9 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w10 = new global::Gtk.HBox ();
			w10.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w11 = new global::Gtk.Image ();
			w11.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-close", global::Gtk.IconSize.Menu);
			w10.Add (w11);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w13 = new global::Gtk.Label ();
			w10.Add (w13);
			w9.Add (w10);
			this.remove_button.Add (w9);
			this.hbox.Add (this.remove_button);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox [this.remove_button]));
			w17.Position = 5;
			w17.Expand = false;
			w17.Fill = false;
			this.Add (this.hbox);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.title_checkbutton.Toggled += new global::System.EventHandler (this.OnTitleCheckbuttonToggled);
			this.view_togglebutton.Toggled += new global::System.EventHandler (this.OnViewTogglebuttonToggled);
			this.freeze_togglebutton.Toggled += new global::System.EventHandler (this.OnFreezeTogglebuttonToggled);
			this.up_button.Clicked += new global::System.EventHandler (this.OnUpButtonClicked);
			this.down_button.Clicked += new global::System.EventHandler (this.OnDownButtonClicked);
			this.remove_button.Clicked += new global::System.EventHandler (this.OnRemoveButtonClicked);
		}
	}
}
