
// This file has been generated by the GUI designer. Do not modify.
namespace CatEye
{
	public partial class StageOperationParametersWidget
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget CatEye.StageOperationParametersWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "CatEye.StageOperationParametersWidget";
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
