
// This file has been generated by the GUI designer. Do not modify.
namespace CatEye.UI.Gtk
{
	public partial class AskToOpenRawDialog
	{
		private global::Gtk.VBox vbox2;
		private global::Gtk.Label found_label;
		private global::CatEye.UI.Gtk.Widgets.RawPreviewWidget rawpreviewwidget;
		private global::CatEye.UI.Gtk.Widgets.PreScaleSelectorWidget prescaleselectorwidget;
		private global::Gtk.Button buttonCancel;
		private global::Gtk.Button buttonOpen;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget CatEye.UI.Gtk.AskToOpenRawDialog
			this.Name = "CatEye.UI.Gtk.AskToOpenRawDialog";
			this.Title = global::Mono.Unix.Catalog.GetString ("RAW file found");
			this.Icon = global::Gdk.Pixbuf.LoadFromResource ("CatEye.UI.Gtk.res.cateye-small.png");
			this.TypeHint = ((global::Gdk.WindowTypeHint)(1));
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Modal = true;
			this.Resizable = false;
			this.SkipPagerHint = true;
			this.SkipTaskbarHint = true;
			// Internal child CatEye.UI.Gtk.AskToOpenRawDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 3;
			this.vbox2.BorderWidth = ((uint)(10));
			// Container child vbox2.Gtk.Box+BoxChild
			this.found_label = new global::Gtk.Label ();
			this.found_label.Name = "found_label";
			this.found_label.Xalign = 0F;
			this.found_label.LabelProp = global::Mono.Unix.Catalog.GetString ("label2");
			this.found_label.MaxWidthChars = 40;
			this.vbox2.Add (this.found_label);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.found_label]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			w2.Padding = ((uint)(4));
			// Container child vbox2.Gtk.Box+BoxChild
			this.rawpreviewwidget = new global::CatEye.UI.Gtk.Widgets.RawPreviewWidget ();
			this.rawpreviewwidget.Events = ((global::Gdk.EventMask)(256));
			this.rawpreviewwidget.Name = "rawpreviewwidget";
			this.vbox2.Add (this.rawpreviewwidget);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.rawpreviewwidget]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			w3.Padding = ((uint)(4));
			// Container child vbox2.Gtk.Box+BoxChild
			this.prescaleselectorwidget = new global::CatEye.UI.Gtk.Widgets.PreScaleSelectorWidget ();
			this.prescaleselectorwidget.Events = ((global::Gdk.EventMask)(256));
			this.prescaleselectorwidget.Name = "prescaleselectorwidget";
			this.prescaleselectorwidget.Value = 0;
			this.vbox2.Add (this.prescaleselectorwidget);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.prescaleselectorwidget]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			w1.Add (this.vbox2);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(w1 [this.vbox2]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Internal child CatEye.UI.Gtk.AskToOpenRawDialog.ActionArea
			global::Gtk.HButtonBox w6 = this.ActionArea;
			w6.Name = "dialog_ActionArea";
			w6.Spacing = 5;
			w6.BorderWidth = ((uint)(10));
			w6.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseUnderline = true;
			// Container child buttonCancel.Gtk.Container+ContainerChild
			global::Gtk.Alignment w7 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w8 = new global::Gtk.HBox ();
			w8.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w9 = new global::Gtk.Image ();
			w9.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-cancel", global::Gtk.IconSize.Button);
			w8.Add (w9);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w11 = new global::Gtk.Label ();
			w11.LabelProp = global::Mono.Unix.Catalog.GetString ("_Don't open");
			w11.UseUnderline = true;
			w8.Add (w11);
			w7.Add (w8);
			this.buttonCancel.Add (w7);
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w15 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w6 [this.buttonCancel]));
			w15.Expand = false;
			w15.Fill = false;
			// Container child dialog_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOpen = new global::Gtk.Button ();
			this.buttonOpen.CanDefault = true;
			this.buttonOpen.CanFocus = true;
			this.buttonOpen.Name = "buttonOpen";
			this.buttonOpen.UseStock = true;
			this.buttonOpen.UseUnderline = true;
			this.buttonOpen.Label = "gtk-open";
			this.AddActionWidget (this.buttonOpen, -3);
			global::Gtk.ButtonBox.ButtonBoxChild w16 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w6 [this.buttonOpen]));
			w16.Position = 1;
			w16.Expand = false;
			w16.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 324;
			this.DefaultHeight = 408;
			this.Hide ();
		}
	}
}
